---
- hosts: all
  become: true
  tasks:
    - name: Install pip for python3
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: Install python requirements
      pip:
        requirements: /vagrant/requirements.txt
    - name: Make symlink python->python3 - allows ansible to use django_manage
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
    - name: Setup database (makemigrations)
      django_manage:
        command: 'makemigrations historical_data'
        app_path: '/vagrant/met_data/'
    - name: Setup database (migrate)
      django_manage:
        command: 'migrate'
        app_path: '/vagrant/met_data/'
    - name: Populate database from Met Office data
      django_manage:
        command: "get_data_from_met_office"
        app_path: "/vagrant/met_data/"
    - name: Start the django server in background
      shell: 'cd /vagrant/met_data; nohup python manage.py runserver 0:8000 </dev/null >/dev/null 2>&1 &'
      args:
        chdir: '/vagrant/met_data'
