---
- hosts: all
  become: true
  tasks:
    - name: Install pip for python3
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: Install python requirements
      pip:
        requirements: /vagrant/requirements.txt
