---
- hosts: all
  become: true
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
  tasks:
    - name: Install pip for python3
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: Install python requirements
      pip:
        requirements: /vagrant/requirements.txt
    - name: Make symlink python->python3 - allows ansible to use django_manage
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
    - name: Setup database (makemigrations)
      django_manage:
        command: 'makemigrations historical_data'
        app_path: '/vagrant/met_data/'
    - name: Setup database (migrate)
      django_manage:
        command: 'migrate'
        app_path: '/vagrant/met_data/'
    - name: Populate database from Met Office data
      django_manage:
        command: "get_data_from_met_office"
        app_path: "/vagrant/met_data/"
    - name: Make directory for static files
      file:
        name: "/var/www/met_data/static"
        state: directory
    - name: Collect static files
      django_manage:
        command: 'collectstatic'
        app_path: '/vagrant/met_data/'
    - name: Install gunicorn
      pip:
        name: gunicorn
    - name: Copy over gunicorn config
      copy:
        src: "gunicorn.conf"
        dest: "/etc/gunicorn/"
    - name: Copy over gunicorn service file
      copy:
        src: "gunicorn.service"
        dest: "/etc/systemd/system/gunicorn.service"
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: Copy over nginx configuration file
      copy:
        src: "nginx.conf"
        dest: "/etc/nginx/nginx.conf"
      notify:
        - reload nginx
    - name: Start gunicorn server
      service:
        name: gunicorn
        state: started
